export const products = [
    {
        id: 1,
        productName: "Wireless Headphones",
        purchaseUnit: "Piece",
        price: 99.99,
        availableUnit: 150,
        category: "Electronics",
        views: 1200,
        status: "Active",
        description: "Experience high-quality sound with these wireless headphones. They feature advanced noise cancellation technology for uninterrupted listening. The lightweight design ensures comfort during extended use. Perfect for music lovers and professionals alike.",
        createdAt: "2025-01-15",
        updatedAt: "2025-05-01",
    },
    {
        id: 2,
        productName: "Smartphone Case",
        purchaseUnit: "Piece",
        price: 19.99,
        availableUnit: 500,
        category: "Accessories",
        views: 800,
        status: "Active",
        description: "Protect your smartphone with this durable and stylish case. It is designed to absorb shocks and prevent scratches. The slim profile ensures it fits easily in your pocket. Available in multiple colors to match your style.",
        createdAt: "2025-02-10",
        updatedAt: "2025-04-25",
    },
    {
        id: 3,
        productName: "Gaming Mouse",
        purchaseUnit: "Piece",
        price: 49.99,
        availableUnit: 200,
        category: "Electronics",
        views: 950,
        status: "Active",
        description: "Enhance your gaming experience with this ergonomic gaming mouse. It features customizable buttons and adjustable DPI settings. The sleek design ensures a comfortable grip during long gaming sessions. Built for precision and speed.",
        createdAt: "2025-03-05",
        updatedAt: "2025-05-05",
    },
    {
        id: 4,
        productName: "Office Chair",
        purchaseUnit: "Piece",
        price: 199.99,
        availableUnit: 75,
        category: "Furniture",
        views: 600,
        status: "Inactive",
        description: "Sit comfortably for hours with this adjustable office chair. It features a padded seat and backrest for maximum support. The height and tilt can be customized to suit your needs. Ideal for home or office use.",
        createdAt: "2025-01-20",
        updatedAt: "2025-03-15",
    },
    {
        id: 5,
        productName: "LED Desk Lamp",
        purchaseUnit: "Piece",
        price: 29.99,
        availableUnit: 300,
        category: "Home & Office",
        views: 450,
        status: "Active",
        description: "Brighten your workspace with this energy-efficient LED desk lamp. It offers adjustable brightness levels to suit your needs. The modern design complements any desk setup. Perfect for reading, studying, or working.",
        createdAt: "2025-04-01",
        updatedAt: "2025-05-08",
    },
    {
        id: 6,
        productName: "Bluetooth Speaker",
        purchaseUnit: "Piece",
        price: 59.99,
        availableUnit: 120,
        category: "Electronics",
        views: 1100,
        status: "Active",
        description: "Enjoy your favorite music anywhere with this portable Bluetooth speaker. It delivers crystal-clear sound and deep bass. The compact design makes it easy to carry. Perfect for parties, picnics, or home use.",
        createdAt: "2025-02-15",
        updatedAt: "2025-05-02",
    },
    {
        id: 7,
        productName: "Running Shoes",
        purchaseUnit: "Pair",
        price: 89.99,
        availableUnit: 250,
        category: "Sportswear",
        views: 700,
        status: "Active",
        description: "Run comfortably with these lightweight running shoes. They are designed for all terrains and provide excellent grip. The breathable material keeps your feet cool and dry. Perfect for athletes and casual runners.",
        createdAt: "2025-03-10",
        updatedAt: "2025-05-06",
    },
    {
        id: 8,
        productName: "Yoga Mat",
        purchaseUnit: "Piece",
        price: 25.99,
        availableUnit: 400,
        category: "Fitness",
        views: 500,
        status: "Inactive",
        description: "Practice yoga with confidence on this non-slip yoga mat. It provides excellent cushioning for your joints. The lightweight design makes it easy to carry to the studio. Ideal for yoga, pilates, or home workouts.",
        createdAt: "2025-01-25",
        updatedAt: "2025-04-30",
    },
    {
        id: 9,
        productName: "Laptop Stand",
        purchaseUnit: "Piece",
        price: 39.99,
        availableUnit: 180,
        category: "Accessories",
        views: 850,
        status: "Active",
        description: "Improve your posture with this adjustable laptop stand. It is designed to elevate your laptop to eye level. The sturdy build ensures stability during use. Perfect for home, office, or travel.",
        createdAt: "2025-02-05",
        updatedAt: "2025-05-03",
    },
    {
        id: 10,
        productName: "Water Bottle",
        purchaseUnit: "Piece",
        price: 15.99,
        availableUnit: 600,
        category: "Home & Office",
        views: 400,
        status: "Active",
        description: "Stay hydrated with this reusable water bottle. It features a leak-proof design and a wide mouth for easy cleaning. The durable material ensures long-lasting use. Ideal for gym, office, or outdoor activities.",
        createdAt: "2025-03-01",
        updatedAt: "2025-05-07",
    },
    {
        id: 11,
        productName: "Smartwatch",
        purchaseUnit: "Piece",
        price: 199.99,
        availableUnit: 90,
        category: "Electronics",
        views: 1300,
        status: "Inactive",
        description: "Track your fitness and stay connected with this feature-packed smartwatch. It includes heart rate monitoring, GPS, and notifications. The sleek design makes it suitable for any occasion. Perfect for tech enthusiasts and fitness lovers.",
        createdAt: "2025-02-20",
        updatedAt: "2025-05-04",
    },
    {
        id: 12,
        productName: "Desk Organizer",
        purchaseUnit: "Piece",
        price: 22.99,
        availableUnit: 350,
        category: "Home & Office",
        views: 300,
        status: "Active",
        description: "Keep your workspace tidy with this multi-compartment desk organizer. It is designed to hold pens, papers, and other essentials. The compact design saves space on your desk. Perfect for students and professionals.",
        createdAt: "2025-01-30",
        updatedAt: "2025-04-28",
    },
    {
        id: 13,
        productName: "Electric Kettle",
        purchaseUnit: "Piece",
        price: 49.99,
        availableUnit: 200,
        category: "Kitchen Appliances",
        views: 750,
        status: "Active",
        description: "Boil water quickly and safely with this electric kettle. It features an auto shut-off function for added safety. The sleek design fits perfectly in any kitchen. Ideal for tea, coffee, and instant meals.",
        createdAt: "2025-03-15",
        updatedAt: "2025-05-05",
    },
    {
        id: 14,
        productName: "Backpack",
        purchaseUnit: "Piece",
        price: 69.99,
        availableUnit: 220,
        category: "Accessories",
        views: 650,
        status: "Inactive",
        description: "Carry your essentials in style with this durable backpack. It features multiple compartments for better organization. The padded straps ensure comfort during long use. Perfect for travel, school, or work.",
        createdAt: "2025-02-25",
        updatedAt: "2025-05-01",
    },
    {
        id: 15,
        productName: "Wireless Keyboard",
        purchaseUnit: "Piece",
        price: 45.99,
        availableUnit: 150,
        category: "Electronics",
        views: 900,
        status: "Active",
        description: "Type comfortably with this compact wireless keyboard. It features a long battery life and a sleek design. The keys are responsive and quiet, making it ideal for work or gaming. Compatible with multiple devices.",
        createdAt: "2025-03-20",
        updatedAt: "2025-05-06",
    },
    {
        id: 16,
        productName: "Sunglasses",
        purchaseUnit: "Piece",
        price: 29.99,
        availableUnit: 300,
        category: "Fashion",
        views: 500,
        status: "Active",
        description: "Protect your eyes in style with these UV-protected sunglasses. They are lightweight and comfortable for all-day wear. The modern design suits any outfit. Perfect for outdoor activities and casual use.",
        createdAt: "2025-01-18",
        updatedAt: "2025-04-29",
    },
    {
        id: 17,
        productName: "Portable Charger",
        purchaseUnit: "Piece",
        price: 39.99,
        availableUnit: 250,
        category: "Electronics",
        views: 1000,
        status: "Active",
        description: "Keep your devices powered on the go with this portable charger. It features a high-capacity battery for multiple charges. The compact design makes it easy to carry. Perfect for travel, work, or emergencies.",
        createdAt: "2025-02-12",
        updatedAt: "2025-05-02",
    },
    {
        id: 18,
        productName: "Coffee Maker",
        purchaseUnit: "Piece",
        price: 89.99,
        availableUnit: 120,
        category: "Kitchen Appliances",
        views: 800,
        status: "Active",
        description: "Brew your favorite coffee with this programmable coffee maker. It offers multiple brew settings for customized coffee. The sleek design fits perfectly in any kitchen. Ideal for coffee enthusiasts and busy mornings.",
        createdAt: "2025-03-08",
        updatedAt: "2025-05-03",
    },
    {
        id: 19,
        productName: "Fitness Tracker",
        purchaseUnit: "Piece",
        price: 79.99,
        availableUnit: 140,
        category: "Fitness",
        views: 950,
        status: "Active",
        description: "Monitor your health and fitness with this waterproof fitness tracker. It includes heart rate monitoring, step tracking, and sleep analysis. The lightweight design ensures comfort during workouts. Perfect for fitness enthusiasts.",
        createdAt: "2025-02-18",
        updatedAt: "2025-05-04",
    },
    {
        id: 20,
        productName: "Table Lamp",
        purchaseUnit: "Piece",
        price: 34.99,
        availableUnit: 280,
        category: "Home & Office",
        views: 400,
        status: "Active",
        description: "Illuminate your space with this modern table lamp. It features touch controls for easy operation. The adjustable brightness levels suit any mood or task. Perfect for bedrooms, offices, or living rooms.",
        createdAt: "2025-03-12",
        updatedAt: "2025-05-07",
    },
    {
        id: 21,
        productName: "Noise-Cancelling Earbuds",
        purchaseUnit: "Piece",
        price: 79.99,
        availableUnit: 180,
        category: "Electronics",
        views: 950,
        status: "Active",
        description: "Immerse yourself in music with these noise-cancelling earbuds. They provide crystal-clear sound and block out external noise. The compact design ensures a comfortable fit for extended use. Perfect for travel, work, or relaxation.",
        createdAt: "2025-03-15",
        updatedAt: "2025-05-08",
    },
    {
        id: 22,
        productName: "Electric Scooter",
        purchaseUnit: "Piece",
        price: 499.99,
        availableUnit: 50,
        category: "Transportation",
        views: 1200,
        status: "Active",
        description: "Commute in style with this eco-friendly electric scooter. It features a powerful motor and long-lasting battery. The foldable design makes it easy to store and carry. Ideal for urban travel and short commutes.",
        createdAt: "2025-02-28",
        updatedAt: "2025-05-05",
    },
    {
        id: 23,
        productName: "Digital Camera",
        purchaseUnit: "Piece",
        price: 299.99,
        availableUnit: 80,
        category: "Electronics",
        views: 1100,
        status: "Active",
        description: "Capture stunning photos and videos with this digital camera. It features high-resolution imaging and multiple shooting modes. The lightweight design makes it easy to carry. Perfect for photography enthusiasts and travelers.",
        createdAt: "2025-01-22",
        updatedAt: "2025-05-06",
    },
    {
        id: 24,
        productName: "Smart Thermostat",
        purchaseUnit: "Piece",
        price: 149.99,
        availableUnit: 100,
        category: "Home Automation",
        views: 700,
        status: "Active",
        description: "Control your home's temperature with this smart thermostat. It features remote access via a mobile app and energy-saving modes. The sleek design blends seamlessly with any decor. Perfect for modern homes.",
        createdAt: "2025-03-10",
        updatedAt: "2025-05-04",
    },
    {
        id: 25,
        productName: "Wireless Charger",
        purchaseUnit: "Piece",
        price: 29.99,
        availableUnit: 300,
        category: "Accessories",
        views: 850,
        status: "Active",
        description: "Charge your devices effortlessly with this wireless charger. It supports fast charging for compatible devices. The compact and sleek design fits any desk or nightstand. Perfect for home or office use.",
        createdAt: "2025-02-18",
        updatedAt: "2025-05-07",
    },
    {
        id: 26,
        productName: "Smart Light Bulb",
        purchaseUnit: "Piece",
        price: 19.99,
        availableUnit: 400,
        category: "Home Automation",
        views: 600,
        status: "Active",
        description: "Illuminate your home with this smart light bulb. It offers adjustable brightness and color settings via a mobile app. The energy-efficient design reduces electricity costs. Perfect for creating the perfect ambiance.",
        createdAt: "2025-01-30",
        updatedAt: "2025-05-03",
    },
    {
        id: 27,
        productName: "Action Camera",
        purchaseUnit: "Piece",
        price: 199.99,
        availableUnit: 120,
        category: "Electronics",
        views: 950,
        status: "Active",
        description: "Record your adventures with this compact action camera. It features 4K video recording and waterproof housing. The lightweight design makes it easy to carry anywhere. Perfect for outdoor enthusiasts and vloggers.",
        createdAt: "2025-03-05",
        updatedAt: "2025-05-02",
    },
    {
        id: 28,
        productName: "Electric Toothbrush",
        purchaseUnit: "Piece",
        price: 49.99,
        availableUnit: 250,
        category: "Personal Care",
        views: 500,
        status: "Active",
        description: "Maintain oral hygiene with this electric toothbrush. It features multiple cleaning modes and a long-lasting battery. The ergonomic design ensures a comfortable grip. Perfect for daily use and travel.",
        createdAt: "2025-02-12",
        updatedAt: "2025-05-01",
    },
    {
        id: 29,
        productName: "Gaming Chair",
        purchaseUnit: "Piece",
        price: 249.99,
        availableUnit: 60,
        category: "Furniture",
        views: 800,
        status: "Active",
        description: "Game in comfort with this ergonomic gaming chair. It features adjustable armrests, lumbar support, and a reclining backrest. The durable build ensures long-lasting use. Perfect for gamers and professionals.",
        createdAt: "2025-03-20",
        updatedAt: "2025-05-06",
    },
    {
        id: 30,
        productName: "Drone with Camera",
        purchaseUnit: "Piece",
        price: 399.99,
        availableUnit: 40,
        category: "Electronics",
        views: 1300,
        status: "Active",
        description: "Capture breathtaking aerial footage with this drone. It features a high-resolution camera and stable flight controls. The foldable design makes it easy to carry. Perfect for photographers and hobbyists.",
        createdAt: "2025-02-25",
        updatedAt: "2025-05-08",
    },
];

export default products;